version: "3.9"  # optional since v1.27.0
services:
  study-buddy:
    container_name: study-buddy
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - sql
  sql:
    image: "mcr.microsoft.com/mssql/server:latest"
    container_name: sql
    user: root
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=emF3Kos@w1q
    volumes:
      - dbdata:/var/opt/mssql/data

volumes:
  dbdata: